export { Modal } from './parts/Modal'
export * from './parts/Action'
export * from './parts/Actions'
export * from './parts/Body'
export * from './parts/Title'
export * from './parts/SubTitle'
export * from './parts/Header'
export * from './parts/Inset'
export * from './type'
export * from './useModal'
