// NavBar 상수
export const DEFINE_NAVBAR_WIDTH = 40
export const DEFINE_NAVBAR_ITEM_WIDTH = DEFINE_NAVBAR_WIDTH
export const DEFINE_NAVBAR_ITEM_HEIGHT = DEFINE_NAVBAR_WIDTH

// Sidebar 상수
export const DEFINE_SIDEBAR_LEFT_POSITION = DEFINE_NAVBAR_WIDTH
export const DEFINE_SIDEBAR_HEADER_HEIGHT = 43
export const DEFINE_SIDEBAR_SEARCH_HEIGHT = 38
export const DEFINE_SIDEBAR_ABSOLUTE_TOP_BLANK_SCROLL_HEIGHT =
  DEFINE_SIDEBAR_HEADER_HEIGHT + DEFINE_SIDEBAR_SEARCH_HEIGHT
export const DEFINE_SIDEBAR_WIDTH = 240

// Header 상수
export const DEFINE_HEADER_LEFT_POSITION = DEFINE_NAVBAR_WIDTH + DEFINE_SIDEBAR_WIDTH
export const DEFINE_HEADER_HEIGHT = 60
export const DEFINE_SAFE_SCROLL_WIDTH = 24

// 기타 상수
export const DEFINE_CONTENTS_MIN_WIDTH = 320
export const DEFINE_ICON_SIZE = 18

export const DEFINE_CONTENTS_PADDING = 24
