export const DEFINE_CONTENTS_PADDING = 28
export const DEFINE_CONTENTS_MIN_WIDTH = 320
export const DEFINE_CONTENTS_WIDTH = 720
export const DEFINE_CONTENTS_HEADER_ICON = 60
export const DEFINE_CONTENTS_HEADER_PADDING_TOP = 60

export const DEFINE_ICON_SIZE = 18
